### ISSUE TITLE
Docker images are not tagged with build version in GitHub Actions

### ISSUE THREAD

**Issue by robwhitby** [springernature/halfpipe#105]
In the `docker-push` task we tag the image with the build version in Concourse. This doesn't exist in actions but we could use something like workflow run id (need to check exactly).

[discussion in slack](https://springernature.slack.com/archives/C01DWDGRM47/p1645103039830209)

**Comment by efasel** [comment]
I think the problem here is that the GitHub actions workflow was generated long time ago. Recreating it with the current halfpipe version yields:

```
# Generated using halfpipe cli version 3.86.0
name: ee-kong-example
"on":
  push:
    branches:
    - main
    paths:
    - example**
    - .github/workflows/ee-kong-example.yml
  workflow_dispatch: {}
env:
  ARTIFACTORY_PASSWORD: ${{ secrets.EE_ARTIFACTORY_PASSWORD }}
  ARTIFACTORY_URL: ${{ secrets.EE_ARTIFACTORY_URL }}
  ARTIFACTORY_USERNAME: ${{ secrets.EE_ARTIFACTORY_USERNAME }}
  BUILD_VERSION: 2.${{ github.run_number }}.0
  GIT_REVISION: ${{ github.sha }}
  RUNNING_IN_CI: "true"
  VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
  VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
defaults:
  run:
    working-directory: example
concurrency: ${{ github.workflow }}
jobs:
  docker-push:
    name: docker-push
    runs-on: ee-runner
    timeout-minutes: 60
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: example
        file: example/Dockerfile
        push: true
        tags: |
          eu.gcr.io/halfpipe-io/ee-kong-example:latest
          eu.gcr.io/halfpipe-io/ee-kong-example:${{ env.BUILD_VERSION }}
    - name: Repository dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.EE_REPOSITORY_DISPATCH_TOKEN }}
        event-type: docker-push:eu.gcr.io/halfpipe-io/ee-kong-example
```
The image will be tagged with `${{ env.BUILD_VERSION }}` which is defined as `2.${{ github.run_number }}.0`
