### ISSUE TITLE
artifactory vars missing missing in actions workflow output

### ISSUE THREAD

**Issue by robwhitby** [springernature/halfpipe#137]
from @jshiell in [slack](https://springernature.slack.com/archives/C6THTT5SB/p1657109976737109)

The docker-push target in Halfpipe seems to behave differently between GHA and Concourse. My expectation is that we should have the Artifactory vars availability during the image build, and indeed on Concourse that seems correct.

```yaml
  - params:
      build: git/csp-logger
      build_args:
        ARTIFACTORY_PASSWORD: ((artifactory.password))
        ARTIFACTORY_URL: ((artifactory.url))
        ARTIFACTORY_USERNAME: ((artifactory.username))
        RUNNING_IN_CI: "true"
      dockerfile: git/csp-logger/Dockerfile
      tag_as_latest: true
      tag_file: version/number
```

However in Actions we don’t seem to get any build-args at all:
```yaml
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: csp-logger
        file: csp-logger/Dockerfile
        push: true
        tags: |
          eu.gcr.io/halfpipe-io/csp-logger:latest
          eu.gcr.io/halfpipe-io/csp-logger:${{ env.BUILD_VERSION }}
```

If I add explicit vars in Halfpipe, then they seem to get passed into the Actions task as env rather than the expected with.build-args:

```yaml
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: csp-logger
        file: csp-logger/Dockerfile
        push: true
        tags: |
          eu.gcr.io/halfpipe-io/csp-logger:latest
          eu.gcr.io/halfpipe-io/csp-logger:${{ env.BUILD_VERSION }}
      env:
        FOO: bar
```
