### ISSUE TITLE
Halfpipe: support latest CF manifest schema

### ISSUE THREAD

**Issue by robwhitby** [springernature/halfpipe#142]
The CF manifest format has changed and we now don't support some features. We support opting for v6 or v7 CLI but parse the CF manifest as if it was v6. And now v8 of the CLI has been released. Ideally we would support the new schema and be backwards compatible, but maybe we can drop support for v6?

This affects the halfpipe cli (read-only for linting) and the cf deploy resource, where we read some fields (e.g. routes) and then update the env map with vars from the halfpipe manifest.

---

e.g. change to the `services` key

old

```
services:
- service1
- service2
```

new

```
services:
- name: my-service1
  parameters: 
    foo: bar
    herp: derp
- name: my-service2
  parameters: 
    foo: bar
```

Original thread: https://springernature.slack.com/archives/C6THTT5SB/p1626779213429100
