### ISSUE TITLE
Halfpipe: Refactor to stop using the deprecated `docker-image` resource

### ISSUE THREAD

**Issue by robwhitby** [springernature/halfpipe#146]
The `docker-image` resource from Concourse is deprecated. We already use the new `registry-image` resource everywhere except docker push jobs.

https://github.com/concourse/concourse/milestone/59

https://github.com/concourse/registry-image-resource#comparison-to-docker-image-resource

**Comment by simonjohansson** [comment]
- [ ] Build and push a basic docker image
- [ ] Build and push a docker image that takes a file from a previous task
- [ ] Build and push a docker image that takes a file form a previous task and uses a random dockerfile_path and build_path.

**Comment by simonjohansson** [comment]
Build and push a basic docker image.

```
jobs:
- name: build
  plan:
    - attempts: 2
      get: git
      timeout: 15m
      trigger: true
    - task: build
      privileged: true
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: concourse/oci-build-task
        inputs:
          - name: git
            path: .
        outputs:
          - name: image
        run:
          path: build
    - put: simon-test-simple
      params:
        image: image/image.tar
        version: 6.6.6
resources:
- check_every: 10m
  name: git
  source:
    branch: main
    private_key: ((halfpipe-github.private_key))
    uri: git@github.com:springernature/simon-test-new-docker-resource.git
  type: git
- name: simon-test-simple
  type: registry-image
  source:
    repository: eu.gcr.io/halfpipe-io/engineering-enablement/simon-test-simple
    username: _json_key
    password: ((halfpipe-gcr.private_key))
```
