### ISSUE TITLE
actions - fix handling of '.' in watched-paths config

### ISSUE THREAD

**Issue by robwhitby** [springernature/halfpipe#213]
setting watched path to `.` renders the wrong thing in the actions workflow:

```yaml
triggers:
- type: git
  watched_paths:
  - .
```

```yaml
"on":
  push:
    branches:
    - main
    paths:
    - .**     # this is no good
    - .github/workflows/ee-modernisation-cranetest.yml
 ```
