### ISSUE TITLE
artifact restore path is wrong for docker push jobs

### ISSUE THREAD

**Issue by robwhitby** [springernature/halfpipe#23]
Elmar reported this:

Our current understanding: previously when restoring artifacts the artifacts were restored relative to the pipeline, example:
```yaml
  - task: Copying git repo and artifacts to a temporary build dir
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
      run:
        path: /bin/sh
        args:
        - -c
        - |-
          cp -r git/. docker_build
          cp -r artifacts/. docker_build/templates/automated-task/task
      inputs:
      - name: git
      - name: artifacts
      outputs:
      - name: docker_build
```
See the line `cp -r artifacts/. docker_build/templates/automated-task/task`

Now it looks like this:
```yaml
  - task: Copying git repo and artifacts to a temporary build dir
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
      run:
        path: /bin/sh
        args:
        - -c
        - |-
          cp -r git/. docker_build
          cp -r artifacts/. docker_build
      inputs:
      - name: git
      - name: artifacts
      outputs:
      - name: docker_build
    timeout: 1h
```

see: `cp -r artifacts/. docker_build`

In consequence artifacts are not found anymore during a docker build run.

We think this was changed four days ago with this commit: https://github.com/springernature/halfpipe/commit/4c6497681230ab8b6f94366af9806d02cd232084
