### ISSUE TITLE
Allow parallel tasks to contain sequential subtasks.

### ISSUE THREAD

**Issue by simonjohansson** [springernature/halfpipe#52]
```
tasks:
- type: parallel
  tasks:
  - type: seq
     tasks: 
     - type: run
     - type: run
  - type: seq
    tasks:
    - type: run
    - type: run
```
