### ISSUE TITLE
Execute a task for every branch

### ISSUE THREAD

**Issue by robwhitby** [springernature/halfpipe#66]
in the update pipeline job we could detect all the branches and generate a resource + job for each branch.

in halfpipe it could look something like

```yaml
branch-task:   
- type: docker-compose
  name: build
```

it would require teams to be sensible and manage the number of branches in their repos. Maybe we limit it to 10 or something.
