### ISSUE TITLE
Check if overlay is doable, in test.

### ISSUE THREAD

**Issue by simonjohansson** [springernature/halfpipe#68]
Btrfs does strange things under load and Concourse are switching back to overlay as default.

Back in the day, overlay was slow for privileged containers, is this still the case?

- [x] Make sure 5.7 is deploy in a clean slate in test
- [ ] Run some docker-compose and run task pipelines 10 times, note down avarage time.
- [ ] Change to overlay in k8s deployment, and recreate workers
- [ ] Run same tests as #2
- [ ] Diff

**Comment by simonjohansson** [comment]
3 workers, 5.7 deployed on test

**Comment by simonjohansson** [comment]
docker-compose pipeline
```
# Generated using halfpipe cli version 3.24.0
resources:
- name: git
  type: git
  source:
    branch: master
    paths:
    - docker-compose
    private_key: ((halfpipe-github.private_key))
    uri: git@github.com:springernature/halfpipe-examples.git
  check_every: 10m
jobs:
- name: build
  serial: true
  plan:
  - in_parallel:
      steps:
      - get: git
        trigger: true
        attempts: 2
      fail_fast: true
    timeout: 1h
  - task: build
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          password: ((halfpipe-gcr.private_key))
          repository: eu.gcr.io/halfpipe-io/halfpipe-docker-compose
          tag: stable
          username: _json_key
      params:
        ARTIFACTORY_PASSWORD: ((artifactory.password))
        ARTIFACTORY_URL: ((artifactory.url))
        ARTIFACTORY_USERNAME: ((artifactory.username))
        GCR_PRIVATE_KEY: ((halfpipe-gcr.private_key))
        HALFPIPE_CACHE_TEAM: engineering-enablement
        HELLO: world
        YOLO: "420"
      run:
        path: docker.sh
        args:
        - -c
        - |
          if [ -e /etc/alpine-release ]
          then
            echo "WARNING: you are running your build in a Alpine image or one that is based on the Alpine"
            echo "There is a known issue where DNS resolving does not work as expected"
            echo "https://github.com/gliderlabs/docker-alpine/issues/255"
            echo "If you see any errors related to resolving hostnames the best course of action is to switch to another image"
            echo "we recommend debian:stretch-slim as an alternative"
            echo ""
            echo ""
          fi

          export GIT_REVISION=`cat ../.git/ref`

          \docker login -u _json_key -p "$GCR_PRIVATE_KEY" https://eu.gcr.io
          docker-compose  run -e ARTIFACTORY_PASSWORD -e ARTIFACTORY_URL -e ARTIFACTORY_USERNAME -e GIT_REVISION -e HALFPIPE_CACHE_TEAM -e HELLO -e YOLO -v /var/halfpipe/cache:/var/halfpipe/cache -v /var/halfpipe/shared-cache:/var/halfpipe/shared-cache app

          EXIT_STATUS=$?
          if [ $EXIT_STATUS != 0 ] ; then
            exit 1
          fi
        dir: git/docker-compose
      inputs:
      - name: git
      caches:
      - path: ../../../var/halfpipe/cache
      - path: ../../../halfpipe-cache
    timeout: 1h
    attempts: 1
```

Run task pipeline
```
# Generated using halfpipe cli version 3.24.0
resources:
- name: git
  type: git
  source:
    branch: master
    paths:
    - kotlin
    private_key: ((halfpipe-github.private_key))
    uri: git@github.com:springernature/halfpipe-examples.git
  check_every: 10m
jobs:
- name: build
  serial: true
  plan:
  - in_parallel:
      steps:
      - get: git
        trigger: true
        attempts: 2
      fail_fast: true
    timeout: 1h
  - task: build
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: openjdk
          tag: 8-slim-stretch
      params:
        ARTIFACTORY_PASSWORD: ((artifactory.password))
        ARTIFACTORY_URL: ((artifactory.url))
        ARTIFACTORY_USERNAME: ((artifactory.username))
      run:
        path: /bin/sh
        args:
        - -c
        - |
          which bash > /dev/null
          if [ $? != 0 ]; then
            echo "WARNING: Bash is not present in the docker image"
            echo "If your script depends on bash you will get a strange error message like:"
            echo "  sh: yourscript.sh: command not found"
            echo "To fix, make sure your docker image contains bash!"
            echo ""
            echo ""
          fi

          if [ -e /etc/alpine-release ]
          then
            echo "WARNING: you are running your build in a Alpine image or one that is based on the Alpine"
            echo "There is a known issue where DNS resolving does not work as expected"
            echo "https://github.com/gliderlabs/docker-alpine/issues/255"
            echo "If you see any errors related to resolving hostnames the best course of action is to switch to another image"
            echo "we recommend debian:stretch-slim as an alternative"
            echo ""
            echo ""
          fi

          export GIT_REVISION=`cat ../.git/ref`

          ./build.sh
          EXIT_STATUS=$?
          if [ $EXIT_STATUS != 0 ] ; then
            exit 1
          fi
        dir: git/kotlin
      inputs:
      - name: git
      caches:
      - path: ../../../var/halfpipe/cache
      - path: ../../../halfpipe-cache
    timeout: 1h
    attempts: 1
```

10 instances of each.


```
for i in {1..10}; do
	fly -t engineering-enablement-test set-pipeline -c pipeline.yml -p runTask-$i -n
	for j in {1..10}; do
		fly -t engineering-enablement-test trigger-job -j "runTask-$i/build"
	done;
done 
```

Finally un-pause them all at the same time
```

for pipeline in `fly -t engineering-enablement-test pipelines --json | jq -r '.[].name'`; do
	fly -t engineering-enablement-test unpause-pipeline -p $pipeline
done
```
