### ISSUE TITLE
Look into the weird build issue with dflux's mongodb test that freezes the worker

### ISSUE THREAD

**Issue by simonjohansson** [springernature/halfpipe#70]
https://concourse.halfpipe.io/teams/dflux/pipelines/dflux-feeds-packager

works and is similarly configured to the broken pipeline

https://concourse.halfpipe.io/teams/dflux/pipelines/dflux-customer-content .

**Comment by simonjohansson** [comment]
Figure out the last commit that ran in GoCD and passed.

**Comment by simonjohansson** [comment]
```
team: engineering-enablement
pipeline: dflux-customer-content-test

triggers:
- type: git
  branch: testKafka

tasks:
- type: parallel
  tasks:
  - type: run
    name: run-task
    script: ./build
    docker:
      image: te-docker.docker-registry.tools.springer-sbm.com/fig-env-java-8
  - type: docker-compose
    service: code
    name: docker-compose
```
